XXXXXXXXX
  XXX XXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXX XXX XXXXXXXXXXXX

  XXX
    XXXXXX XXXXX XXXXXXXXX XX XXXX XXXXX XXXX XXX XXXXXXX XXXXXXX XXXX XX
    XXX XXXX XXXXXXX XX XXX XXXXXXXXX XX XXX XXXXXX XX XXXXXXX XX XXXXXXXXX
  XXXX

  XXX
    XXXX XXXXXX XXXXXXX XXXX X
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XX
    XXXX XXXXXXX XX XXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XX XXXXXXXXXXXX XXX XXXX
    XXXX XXX XXXXXX XX XXXXX X
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
  XXXX

  XXXX XXXXXXXXXXXXXXXXXXX
    XXX
      XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXX
  XXXXXX

BBBBBBBBB BB BBBBBBB
XXXXXXXX XXXXXXXXXX XXXXXX XXXXX X
  XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
    XXXXXX XXXXX
  X

  XXXXXX XXXXXX
X

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX X
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
  XX
XXX
BBBBBBBBBBBB
XXXXXXXXXX
