XXXXXXXXX
  XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX

  XXX
    XXXXXXX XXX XX XXXX XX XXXXXXX XXX XX XXXXXX XXXX XXX XXXXXXXX
  XXXX

  XXX
    XXXX XXXX XXXX XXXXXXX XX XXXXXXX XXX XXXX XXX XXXXXX XXXX XXXXXXXXXXXX
    XXXXXXX XX XXXXXX X XXX XXX XX XXXXXXX XXX XXXXX XXXXXXX XXXXX XX XXXX
    XXX XXXX XXX XXXXX XXXX XXX XXXXXX XXX XX XXXX
  XXXX

  XXXX XXXXXXXXXXXXXXXXXXX
    XXX
      XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXX
    XXXX
  XXXXXX

BBBBBBBBB BB BBBBBBB
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXX
XX
BBBBBBBBBBBB
XXXXXXXXXX
