BBBB BBBB

XXXX XXXXXXXXXXXXXXXXXXXXXXXX
	XXXX XXXXXXXXXXXXXXXXXXX
		BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
		XXXX XXXXXXXXXXXXXXXXXX
			XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
			    XXXXXX XXXXX
			    XXXXXXXXXXXXXXXXXXXXXXX X
				XXXXXXXXXXXXXXX
				XXXXXXBB BBBBBBBBBBBXBBBBBX
				BB BBBBBBBBBBB BB BBBB BB BBBBBBBBBBBBB BB BBBBXXXXXXXBBBBB
				BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
				BB BBBBBBBBBBBBBBBBBBBB
					XXXXXXXXXXXXXXXXXXX
				BBBBB
				XXXXXXXXXXX
				XX
			XXXXXXXX
			BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
		XXXXXX
	XXXXXX
XXXXXX