BBBB BBBB

XXXX XXXXXXXXXXXXXXXXXXXXXXXX
	XXXX XXXXXXXXXXXXXXXXXXX
		BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
		XXXX XXXXXXXXXXXXXXXXXX
			XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX
				BB BBBBBBBBBBBBBBBBBBBB
					XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXXXXXXXXXXXXXXXX gettext(u'This field can not be empty') X
				BBBBB
				XXXXXXXXXXXXXXXXXXXX
				XXXXXXBB BBBBBBBBBBBXBBBBBX
				XXXXXXXXXXXXXXX XXXXX
				BB BBBBBBBBBBBXXXXXXXXBBBBB
				BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
				XXXXXXXXXXX
			XX
			BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
		XXXXXX
	XXXXXX
XXXXXX