BBBB BBBB

XXXX XXXXXXXXXXXXXXXXXXXXXXXX
	XXXX XXXXXXXXXXXXXXXXXXX
		BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
		XXXX XXXXXXXXXXXXXXXXXX
			XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
				XXXXXXXXXXXXXXXXXXX X
				XXXXXXBB BBBBBBBBBBBXBBBBBX
				XXXXXXXXXXX XXXXX
				BB BBBBBBBBBBBXXXXXXXXBBBBB
				BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
				BB BBBBBBBBBBBBBBBBBBBB
					XXXXXXXXXXXXXXXXXXX
				BBBBB
				XXXXXXXXXXX
			XX
			BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
		XXXXXX
	XXXXXX
XXXXXX