BBBB BBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
	XXXX XXXXXXXXXXXXXXXXXXX
		BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
		XXXX XXXXXXXXXXXXXXXXXX
			BB BBBBBBBBBBB
			XXXX XXXXXXXXXXXX
				 gettext(u'Currently') XXX XXXXXXX XXXXXXXXXXXXXXXXXXXX
			XXXXXX
			BBBBB
			
			BB BBBBBBBBBBB
				 gettext(u'Change') X
			BBBBB
			XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX
				XXXXXXBB BBBBBBBBBBBXBBBBBX
				XXXXXXXXXXX XXXXX
				BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
				BB BBBBBBBBBBBBBBBBBBBB BBB BBB BBBBBBBBBBB
					XXXXXXXXXXXXXXXXXXX
				BBBBB
				XXXXXXXXXXX 
			XX
			BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
		XXXXXX
	XXXXXX
XXXXXX