BBBB BBBB

XXXX XXXXXXXXXXXXXXXXXXXXXXXX
	XXXX XXXXXXXXXXXXXXXXXXX
		BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
		XXXX XXXXXXXXXXXXXXXXXX
			XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX
				XXXXXXBB BBBBBBBBBBBXBBBBBX
				XXXXXXXXXXXXX XXXXX
				XXXXXXXXXXXXXXXXXXXX
				BB BBBBBBBBBBBXXXXXXXXBBBBB
				BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
				BB BBBBBBBBBBBBBBBBBBBB
					XXXXXXXXXXXXXXXXXXX
				BBBBB
				XXXXXXXXXXX XX
			BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
		XXXXXX
	XXXXXX
XXXXXX