BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
	
    XXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
XXXXXXXX