BBBB BBBB BBBBBBBBBBBB

XXXX XXXXXXXXXXXXXXXXXXXXXXXX
	XXXX XXXXXXXXXXXXXXXXXXX
		BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
		XXXX XXXXXXXXXXXXXXXXX
			XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX
				XXXXXXXXXXXXXXXXXXX X
				XXXXXXBB BBBBBBBBBBBXBBBBBX
				XXXXX
				BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
				BB BBBBBBBBBBBBBBBBBBBB
					XXXXXXXXXXXXXXXXXXX
				BBBBB
				XXXXXXXXXXXX
				BBB BBBBBB BBBB BB BBBBBBBBBBBBBBBBBBB
				XXXXXXX XXXXXXXX BBBBBBB BBBBB BBBBBBBBBBBXXXXXXXXXXXXXXXXXXXBBBBBBBBBBXXXXXXXXXX
				BBBBBB
			XXXXXXXXX
			BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
		XXXXXX
		XXXX XXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXX
				
			XXXXXX
		XXXXXX
	XXXXXX
XXXXXX