BBBB BBBB BBBBBBBBBBBB

XXXX XXXXXXXXXXXXXXXXXXXXXXXX
	XXXX XXXXXXXXXXXXXXXXXXX
		BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
		XXXX XXXXXXXXXXXXXXXXX
		    XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX
				XXXXXXXXXXXXXXXXXXX X
				XXXXXXBB BBBBBBBBBBBXBBBBBX
				XXXXX
				BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
				BB BBBBBBBBBBBBBBBBBBBB
					XXXXXXXXXXXXXXXXXXX
				BBBBB
				XXXXXXXXXXXX
				BBB BBBBBB BBBB BB BBBBBBBBBBBBBBBBBBB
				XXXXXXX XXXXXXXX BB BBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXBBBBBXXXXXXXXXX
				BBBBBB
			XXXXXXXXX
			BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
		XXXXXX
		XXXX XXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXX
				
			XXXXXX
		XXXXXX
	XXXXXX
XXXXXX