BBBB BBBB BBBBBBBBBBBB

XXXX XXXXXXXXXXXXXXXXXXXXXXXX
	XXXX XXXXXXXXXXXXXXXXXXX
		BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
		XXXX XXXXXXXXXXXXXXXXX
			XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX
				XXXXXXXXXXXXXXXXXXX X
				XXXXXXBB BBBBBBBBBBBXBBBBBX
				XXXXX
				BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
				BB BBBBBBBBBBBBBBBBBBBB
					XXXXXXXXXXXXXXXXXXX
				BBBBB
				XXXXXXXXXXXX
				BBB BBBBBB BBBB BB BBBBBBBBBBBBBBBBBBB
				XXXXXXX XXXXXXXX BBBBBBB BBBBB BBBBBBBBBBBXXXXXXXXXXXXXXXXXXXBBBBBBBBBBXXXXXXXXXX
				BBBBBB
			XXXXXXXXX
			BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
		XXXXXX
		XXXX XXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXX
				
			XXXXXX
		XXXXXX
	XXXXXX
XXXXXX