BBBB BBBB

XXXX XXXXXXXXXXXXXXXXXXXXXXXX
	XXXX XXXXXXXXXXXXXXXXXXX
		BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
		XXXX XXXXXXXXXXXXXXXXXX
			XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX
				XXXXXXXXXXXXXXXXXXXX
				XXXXXXBB BBBBBBBBBBBXBBBBBX
				XXXXXXXXXXX XXXXX
				BB BBBBBBBBBBBXXXXXXXXBBBBB
				BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
				BB BBBBBBBBBBBBBBBBBBBB
					XXXXXXXXXXXXXXXXXXX
				BBBBB
				XXXXXXXXXXX XX
			BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
		XXXXXX
	XXXXXX
XXXXXX