XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
  XXXXXX
    BBBBBBB BBBBBBBBBBB
  XXXXXXX
  XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXX XXXXXXXXXXXXXX
      XXXXXX
    XXXX

    BBBBBBB BBBBBBBBBBBBB

    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBB
        BBBBBBB BBBBBBBB
      XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXX
          BBBBBBB BBBBBBBBBBBBB
        XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
          
        XXXXXX
      XXXXXX
    XXXXXX

    BBBBBBB BBBBBBBBBBB
  XXXXXXX
XXXXXXX
