XXXXXXXXX
  XXX XXXXXXXXX
    XXX X XXX XXXXXXX XXXX XX XXX XX XXXXXXXX XXXXXXX
  XXXXX

  XXX
    XXXXXXX XXXXXX XXXX XXXX XXXX XXXX XX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXX XXXX X XXXXXXXX XXXXXXX XX XXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXXX XXXX XXXXXXXX XXX XXX XXXXXXXXXXXXX
  XXXX

  XXXX
    XXX XX X XXXX XXXXXXX XXXXX XX XXXX XXX XXXXXXXX
  XXXXX

  XXX
    XXX XXXX XXX XXX XXXXXXXX XXXXXXX XXX XXXXXXXX XX XXX XXXX XXXXX XXXX XX XXXXXXX XXXX XX XXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXX XXXXXXX XXX XXXXXXX XX XX XXXXXXXXX
  XXXX

  XXX
    XX XXX XXX XXXXX XXXXXXX XX X XXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXX XXXXX XXX XXXXXXX XXXXXX X XXXXX XXXXX XXXXXXX XXX XXX XX XXXX XX XXXX XXXXXXXX XXXXXXXXXXXX XX XXXXXXXX XXXXXX XXX XXX XXXXXXXX XXX XXX XXXXXXXX XX XXX XXX XXXXX XXXXX XXXXX XXX XXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
  XXXX

BBBBBBBBB BB BBBBBBB
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
BBBBBBBBBBBB

  XXXX
    XXXXXXX XX XXXXX XXXXXX XXXXXX XXXXXX XX XX XXXXXXXXXX XXXX
  XXXXX

  XXX
    XXX XX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XX XXXXX XXXXXXXXXXXX XX XXX XXXX XXXXX XXXXX XXXXXXX XXX XXXXXXXXX XXXXXX XXXXXX XXXXXX XX XXXX XXXXXXXX XXXXX XXXXX XXXXXXX XX XXXXX XXXXXXX XXXX XXXXXXX XX XXXXX XXXXXXX XX XXXXX XX XXXX XX XXXX XX XXXX XXXXXXX
  XXXX

  XXX
    XX XXXXXXXXX XX XXXXXXX XXXXXX XX XXXXXX XX XXX XXXX XXXXX XXXXX XXX XXXX XX XXXX XX XXX XXX XXXXXX
  XXXX

  XXXX
    XXXXXX X XXXXX XX XXX XXXXX XX XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXX
  XXXXX

  XXX
    XXXXXXX XXXXXXXXXX XXXX XXX XXX XXX XXXX XXXXX XXXX XX XXXXX XXX XXXXX XXXXXXX XX XXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXX XXX XXXXX XXXXX XXX XXXXX XX XXX XXXXXXXXXXXXXXXX XXXXXXX XX XXXXXXX XXXXXXXX XXXX XXXXX XXXX XXXXXXX XX XXX XXXXXXX XXXXXX XXX XXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXX XXXX XX XXX XXXXXXXX XXX XXXXX XXXXXXX XX XXX XXXXXXXXXXXXXXXXX XXXXXX XXX XXXX XXXXXXXXXXXXXXX XX XXX XXX XXXXX XX XXXX XXXX XX XXX XXXX XX XXXX XX XXX XX XXX XXXXXXX XXXXXXX XXXXXXXX
  XXXX
XXXXXXXXXX