XXXXXXXXX
  XXX XXXXXXXXXXXXX
    XXX XXXXXX XXXXXXX XX XXXXXXXXXXXX
  XXXXX

  XXX
    XXXXXXX XXXX XXXXXXXX XXXXXX XX X XXXXXX XXXXXXXX XX XXX XXX XXX XX XXX XXXXXXXXXXXX XXXXXXX XX XXX XXX XXXX XXXXXXXXXXXXXXXXXXXXXXX XX XXX XXXXXX XXXXXXX XXXXX XXX XXXXX XXXX XX XXXXXXXXXX XXXXXXXX
  XXXX

BBBBBBBBB BB BBBBBBB
XXXXXXXXXXXXXXXXXXXXXX
BBBBBBBBBBBB

  XXX
    XXX XXX XXXXXXXXXX XXXX XX XXXXXX XXXXXXXXXX XXX XX XXX XXXXXXX XXXX XXX XXXXX XXXX XX XXXXXXXXXX XXXXXXX XXXXX
  XXXX

BBBBBBBBB BB BBBBBBB
XXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXX XXXXXXX XX XXXXXXX
XXX
BBBBBBBBBBBB

  XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXX XXXXXXX XX XXX XXX XXX XXXXXXXXXX
  XXXXX

  XXX
    XX XXXX XXXXXX XXX XXXX XX XXX XXX XXXXXXX XXXXXXX XXX XXX XXXXXXXXX XX
    XXXXXXX XX XXXX XXX XXXXXXXXXXXX XXXX XX XXXXXXXXXX XXXXXX XXXX XXX XXX
    XXXXXXXXX XXXX XXXX XXXXXXXX XX XXXXXXXX XX XXX XXX XXXXX XXXXXXXXXXXX
    XXXXXXX XX XXXXXXXXXXXXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX XXXXXXX XXX
    XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX
    XXX XX XXX XXXX XXXXXXXXX
  XXXX

  XXX
    XXXX XXXXXXX XXXXXXX XXXXXXXXX XXX XXXX XXXXXXXX XXXX XXXX XXXX XXX XXXX
    XX XXXXXXXXXX XXXXXXX XXXXXXX XXX XXXX XXXX XXXX XX XXXXXX XX XXXXXXXXX
    XXXX XXX XXX XXXX XXX XXXXXX XXXXXXXXXXXXXXX
  XXXX

  XXX
    XXXXXXXXXXX XXX XXX XXXXXXX XXXXXXXXXXXXXXXX XX XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
  XXXX

BBBBBBBBB BB BBBBBBB
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
BBBBBBBBBBBB

  XXXX
    XXX XXX X XXX X XXXXXXX XXXXX XXX X XXXXXX XXXXXXX
  XXXXX

  XXX
    XXX XXX XXXX XX
    XXX XXXXXX XXXX XXX XXXX XXXXXX XX XXXX XXX XXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX
    XXXXX XXXX XXX XXXXXX XXXXXXXXXXXXXXXXX XXXX XX XXXXXXXX XX X XXXXX XX
    XXXXXXXX XXX X XXXXXX XXXX XXXXXXXXXXXXXXXX XXXX XXXXXXX XX XX X XXXXXXXXX
    XXXXXXX
  XXXX

BBBBBBBBB BB BBBBBBB
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
BBBBBBBBBBBB

  XXXX
    XXX XXX X XXXXX XXX XX XXX XXXXXX XXXXXXX XXXXXXXX
  XXXXX

  XXX
    XXX XXX XXXXX XXX XXXXXXX XXXXXXX XX XXXXX XXXXXXX XXXXXX XX XXXXXXX
  XXXX

BBBBBBBBB BB BBBBBBB
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBBBBBB
XXXXXXXXXX