# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Choice text')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Is correct')),
            ],
            options={
                'verbose_name': 'Choice',
                'verbose_name_plural': 'Choices',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='A short label, generally used in URLs.')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=b'uploads/issue_photo/', verbose_name='Icon')),
                ('status', models.CharField(choices=[(b'd', 'Draft'), (b'p', 'Published'), (b'w', 'Removed')], max_length=1)),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='A short label, generally used in URLs.')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('status', models.CharField(choices=[(b'd', 'Draft'), (b'p', 'Published'), (b'w', 'Removed')], max_length=1)),
                ('issues', models.ManyToManyField(blank=True, related_name='lesson_issues', to='ask.Issue', verbose_name='Issues')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Question text')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='lesson_question', to='ask.Question', verbose_name='Questions'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='requirements',
            field=models.ManyToManyField(blank=True, related_name='lesson_requirements', to='ask.Lesson', verbose_name='Requirements'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask.Question', verbose_name='Question'),
        ),
    ]
