# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 18:11
from __future__ import unicode_literals

import ask.utils.colors
import base.utils.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField(default=False, verbose_name='Correct')),
                ('exists', models.BooleanField(default=True, verbose_name='Exists')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'ordering': ('-date',),
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Choice text')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Is correct')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Choice',
                'verbose_name_plural': 'Choices',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', base.utils.models.AutoSlugField(blank=True, db_index=False, populate_from=b'name', unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=b'uploads/issue_photo/%Y/%m/%d', verbose_name='Icon')),
                ('status', models.CharField(choices=[(b'd', 'Draft'), (b'p', 'Published'), (b'r', 'Removed')], max_length=1)),
                ('color', models.CharField(blank=True, default=ask.utils.colors.get_color, max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', base.utils.models.AutoSlugField(blank=True, db_index=False, populate_from=b'name', unique=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.CharField(choices=[(b'd', 'Draft'), (b'p', 'Published'), (b'r', 'Removed')], max_length=1)),
                ('color', models.CharField(blank=True, default=ask.utils.colors.get_color, max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('issues', models.ManyToManyField(blank=True, related_name='lesson_issues', to='ask.Issue', verbose_name='Issues')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='Position')),
                ('text', models.TextField(verbose_name='Question text')),
                ('help', models.CharField(blank=True, max_length=255, null=True, verbose_name='Help text')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='lesson_question', to='ask.Question', verbose_name='Questions'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='requirements',
            field=models.ManyToManyField(blank=True, related_name='lesson_requirements', to='ask.Lesson', verbose_name='Requirements'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask.Question', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='choices',
            field=models.ManyToManyField(to='ask.Choice', verbose_name='Choices'),
        ),
        migrations.AddField(
            model_name='answer',
            name='lesson',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ask.Lesson', verbose_name='Lesson'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ask.Question', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
