# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0002_auto_20170207_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='Position')),
                ('title', models.TextField(verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['position'],
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
