# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0006_auto_20170201_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='position',
            field=models.IntegerField(default=1, verbose_name='Position'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Regiunicodeation Date'),
        ),
    ]
