# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0007_auto_20170201_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(default=False, verbose_name='Correct'),
        ),
    ]
