# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 12:09
from __future__ import unicode_literals

import base.utils.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0007_video_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='slug',
            field=base.utils.models.AutoSlugField(blank=True, db_index=False, populate_from=b'title', unique=True),
        ),
    ]
