# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0009_auto_20170201_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='exists',
            field=models.BooleanField(default=True, verbose_name='Exists'),
        ),
    ]
