# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0010_remove_video_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('-last_modified',), 'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['-last_modified'], 'verbose_name': 'Choice', 'verbose_name_plural': 'Choices'},
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='date',
            new_name='creation',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='date',
            new_name='creation',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='date',
            new_name='creation',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='date',
            new_name='creation',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='date',
            new_name='creation',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='date',
        ),
        migrations.AddField(
            model_name='answer',
            name='creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='question',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='video',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
