# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0010_answer_exists'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='lesson',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='ask.Lesson', verbose_name='Lesson'),
            preserve_default=False,
        ),
    ]
