# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0011_answer_lesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('-date',), 'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AddField(
            model_name='question',
            name='help',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Help text'),
        ),
    ]
