# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 01:39
from __future__ import unicode_literals

import base.utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0012_auto_20170202_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=b'uploads/issue_photo/%Y/%m/%d', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='slug',
            field=base.utils.models.AutoSlugField(blank=True, db_index=False, populate_from=b'name', unique=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=base.utils.models.AutoSlugField(blank=True, db_index=False, populate_from=b'name', unique=True),
        ),
    ]
