# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0015_auto_20170212_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='position',
            field=models.IntegerField(blank=True, null=True, verbose_name='Position'),
        ),
    ]
