# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ask', '0017_auto_20170212_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('text', models.TextField(verbose_name='Text')),
                ('solved', models.BooleanField(default=False, verbose_name='Solved')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['-last_modified'],
                'verbose_name': 'Choice',
                'verbose_name_plural': 'Choices',
            },
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['position', 'creation', 'last_modified'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['position', 'creation', 'last_modified'], 'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
    ]
