# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0019_report_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-last_modified'], 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
    ]
