# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0023_remove_question_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='course',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Private'),
        ),
    ]
