# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0024_auto_20170314_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Amount'),
        ),
    ]
