# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0025_auto_20170314_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='private',
        ),
        migrations.AddField(
            model_name='course',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='is Private'),
        ),
    ]
