# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-21 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0027_auto_20170721_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='icon',
            field=models.ImageField(default=1, upload_to='uploads/course_icon/%Y/%m/%d', verbose_name='Icon'),
            preserve_default=False,
        ),
    ]
