# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-21 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0029_question_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='lesson',
        ),
    ]
