# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-21 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0030_remove_question_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_private',
        ),
    ]
