# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-21 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0031_auto_20170721_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='correct',
        ),
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Is Correct'),
        ),
    ]
