# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 01:25
from __future__ import unicode_literals

import base.utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Title')),
                ('slug', base.utils.models.AutoSlugField(blank=True, db_index=False, populate_from=b'title')),
            ],
            options={
                'ordering': ['title'],
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
