# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 01:28
from __future__ import unicode_literals

import base.utils.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=base.utils.models.AutoSlugField(blank=True, db_index=False, populate_from=b'title', unique=True),
        ),
    ]
