# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20170204_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[(b'd', 'Draft'), (b'p', 'Published'), (b'w', 'Withdrawn')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
