# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 01:45
from __future__ import unicode_literals

import base.utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_category_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default=1, max_length=75, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=base.utils.models.AutoSlugField(blank=True, db_index=False, populate_from=b'name', unique=True),
        ),
    ]
