# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 02:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_auto_20170209_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='is_closed',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='view_count',
        ),
    ]
