# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 02:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0018_auto_20170222_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-creation'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
