# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-22 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0021_topic_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='created_by',
        ),
        migrations.AddField(
            model_name='topic',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
