XXXXXXXXX
  XXXX
    XXX X XXXXXX XXXX XXXXXX XXXXXXX XXX XXXXXXX
  XXXXX

  XXXX
    XXX XXXXXXX XXXX XXXXX XXX XXXX XXX XXXXX X XXXXXX XXXX XXXXXX XXXXXXXXXX XXX XXXXXXXX
  XXXXX

BBBBBBBBB BB BBBBBBB
XXXXXXXXXXXXXXXXXXXXX
  XXXXX X
    XXXXXX XXX XX XXXX XXX XXXXXXXXXXXX XXXXXX XXXXXXXXXX XXX XXXXXXX
  X
XXX
BBBBBBBBBBBB

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB

  XXXX
    XXXXXXX XX XXXXXXXX XXXX XXXXXX XXXXXX XXX XXXX XX XXXXXXXXXX
  XXXXX

BBBBBBBBB BB BBBBBBB
XXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXX XX XX XXXX XXXXX XXXXX XX XX XX XXXXXXXXXX XXXX
XXX
BBBBBBBBBBBB

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB

  XXXX
    X XXXX XXXX XXX XXXXXX XXX XX XXXXX XXX XXXXXX XXXXXXX
  XXXXX

BBBBBBBBB BB BBBBBBB
XXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXX XX XX XX XXXXX XX XXXXXXX XXXX XX XXXXXXXXX
XXX
BBBBBBBBBBBB

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB

  XXXX
    XXX XXX X XXXXXXXXXXX XXXX XXX XXXXXX XXXX
  XXXXX

BBBBBBBBB BB BBBBBBB
XXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
XXX
BBBBBBBBBBBB

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
XXXXXXXXXX