XXXXXXXXX
  XXXX
    XXX X XXXXXX XXX XXX XXXXXXXX XX XXXXXXX
  XXXXX

  XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXX XXXXXXXX XX XXXXXX XXXXXXXX XXXXX XXX XXXXXXXXX XXXXXXXXXX
  XXXXX

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB

  XXX XXXXXXXXXXXXXXXXXXXX
    XXX X XXXX XX XXXXXXX XXX XXX XXXXXXXX XX XX XXXXXXXX XXX
  XXXXX

BBBBBBBBB BB BBBBBBB
XXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
XXX
BBBBBBBBBBBB

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB

  XXXX
    XXXXXXXX XXXXX X XXXXXXXXX XXXXX XXX X XXXXXXXXXX XXX XXX XXXXXX XXX
  XXXXX

  XXX
    XXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XX XX XXX XXXXXX
  XXXX

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB

  XXXX
    XXXXXXXX XXXXX XXXXXX XX XXX X XXXXXXXXXX XXX XXX XXXXXX XXX
  XXXXX

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
XXXXXXXXXX