XXXXXXXXX
  XXXX
    XXX X XXXXXX XXX XXXXXXXXX XXXXXXX XXXXXX
  XXXXX

  XXXX
    XXX X XXXXXX XXX XXXXXXXXXXX XXXXXX XXXX XXX XXXXXXXX XX XXXXXXX
  XXXXX

BBBBBBBBB BB BBBBBBB
XXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX XXXX
XXX
BBBBBBBBBBBB

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB

  XXXX
    XXX X XXXXXXX XXX XXXXXXXX XXXX XXXXXXX XXXX X XXXXXX XX XXXXXXXXX
  XXXXX

BBBBBBBBB BB BBBBBBB
XXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX XXXXX
XXX
BBBBBBBBBBBB

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
XXXXXXXXXX