XXXXXXXXX
  XXXX
    XXX XXXXXXX XX XXXXXXX XXXXX XX XXX XXXXXX XXXXX
  XXXXX

  XXXX
    XXX XX X XXXXXX XXXXXXXX
  XXXXX

BBBBBBBBB BB BBBBBBB
XXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXX
XXX
BBBBBBBBBBBB

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB

  XXXX
    XXXX XXXXXXX XXXX XXXX X XXXXXX XXXXXXX
  XXXXX

  XXX
    XXXX
  XXXX

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB

  XXXX
    XXX XX X XXX XXXXX XXXXXXXXXX XX XXX XXXX
  XXXXX

BBBBBBBBB BB BBBBBBB
XXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXX XXXXXXXX XXXXXXXX X
    XXX XXXX X XXXXXXXXXXXXXXXXXXXX

    XX XXXXX XXX XXX X
      XXXXXX XXXXX
    X

    XXXXXX X
      XXX XXXXX
      XXXXX XXXXX
      XXXXXXX XXXX XX XXX XXXXXXXXXX XXXXXXXXXX
    X
  X
XXX
BBBBBBBBBBBB

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB

  XXXX
    XXX X XXXXXXX XXXX XXXX XXX XXXXXXXX
  XXXXX

BBBBBBBBB BB BBBBBBB
XXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXX XXXXXXXX XXXXXXXX X
    XX XXXXX XXXXXX XX XXXXXX X XXX XX XXXXX XX XX X XXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXX XXX XXX X
      XX XXXXXX XXXX XX XXXXXXX XXX XXXXXXXX
      XXXXXX XXXXX
    X

    XXXXXX X
      XXX XXXXXXXXXXXX
      XXXXX XXXXXXXXXXX
    X
  X
XXX
BBBBBBBBBBBB

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB

  XXXX
    XXX XX X XXXXXXX XXX XXXXXXXXX XX XXX XXXXXXX
  XXXXX

BBBBBBBBB BB BBBBBBB
XXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXX XXXXXXXX XXXXXX XXXX X
    XX XXXXXX XXX XXX XX XXX XXX XX XXX XXXXXXX
    XXXXXXXXXXXXXXX
  X
XXX
BBBBBBBBBBBB

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
XXXXXXXXXX