XXXXXXXXX XXXXX
XXXXXX
  XXXXXX
    BBBBBBB BBBBBBBBB
  XXXXXXX
  XXXXXX
    BBBBBBB BBBBBBBBBBBBBBB

    

    BBBBBBB BBBBBBBBBBB

    XXXXXXXX
      XXXXXXXXX XXX X
        XXXX XXXXXXXX

        XXXXXXXXXX XX X
          XXX XXXXXXX X XXXXXXXXXX
          XXX XXXXX X XXXXXXXXXXXXXXXXX
          XXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX

          XXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXXX XX
          XXX

          XXXXXXXXXXXXXXXXXX XXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXX

          XXXXXXXXXXXXXXXX
            XXXXXXX X
              XXXX XXXXXXXX XX X
                XXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX

                XXXXXX XXXXXXXXX X XXXXXXXXX X XXXXXXXXXXXXXXXX
              XX
              XXXXXXX XXXXXXXX XX X
                XXXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              X
            X
          XXX
        XXX
      XXXXXXXXXXX

      XXXXXXXXX XX X
        XXXX XXXXXXXX

        XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXX XXXXX
      XXXXX
    XXXXXXXXX

    BBBBBBB BBBBBBB
  XXXXXXX
XXXXXXX
