# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-11 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170611_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'uploads/post_photo/%Y/%m/%d', verbose_name='Image'),
        ),
    ]
