# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-24 18:14
from __future__ import unicode_literals

import base.utils.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Is Correct')),
                ('exists', models.BooleanField(default=True, verbose_name='Exists')),
                ('creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-creation',),
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Choice text')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Is correct')),
                ('creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creation'],
                'verbose_name': 'Choice',
                'verbose_name_plural': 'Choices',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', base.utils.models.AutoSlugField(blank=True, db_index=False, populate_from='name', unique=True)),
                ('position', models.IntegerField(verbose_name='Position')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(max_length=200, verbose_name='Description')),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('r', 'Removed')], max_length=1)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'ordering': ['position'],
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='LearningObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='Position')),
                ('creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['position'],
                'verbose_name': 'Learning Object',
                'verbose_name_plural': 'Learning Objects',
            },
        ),
        migrations.CreateModel(
            name='LearningObjectHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('learning_object', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='courses.LearningObject', verbose_name='Learning Object')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ('-creation',),
                'verbose_name': 'Learning Object History',
                'verbose_name_plural': 'Learning Object History',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', base.utils.models.AutoSlugField(blank=True, db_index=False, populate_from='name', unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(max_length=200, verbose_name='Description')),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('r', 'Removed')], max_length=1)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(blank=True, related_name='lesson_courses', to='courses.Course', verbose_name='Courses')),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('requirements', models.ManyToManyField(blank=True, related_name='lesson_requirements', to='courses.Lesson', verbose_name='Requirements')),
            ],
            options={
                'ordering': ['creation'],
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Question text')),
                ('help', models.CharField(blank=True, max_length=255, null=True, verbose_name='Help text')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'ordering': ['creation'],
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', base.utils.models.AutoSlugField(blank=True, db_index=False, populate_from='title', unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('url', models.URLField(verbose_name='URL')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'ordering': ['-creation'],
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.AddField(
            model_name='learningobject',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slide_lesson', to='courses.Lesson', verbose_name='Lesson'),
        ),
        migrations.AddField(
            model_name='learningobject',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_object_question', to='courses.Question', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Question', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='choices',
            field=models.ManyToManyField(to='courses.Choice', verbose_name='Choices'),
        ),
        migrations.AddField(
            model_name='answer',
            name='lesson',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='Lesson'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Question', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterUniqueTogether(
            name='learningobject',
            unique_together=set([('lesson', 'position')]),
        ),
    ]
