# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-23 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='introduction',
        ),
        migrations.AddField(
            model_name='introduction',
            name='question',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Question', verbose_name='QUestion'),
        ),
    ]
