# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-23 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20170723_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introduction',
            name='created_by',
        ),
    ]
