# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-23 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_introduction_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='created_by',
        ),
    ]
