# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-24 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20170724_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['creation'], 'verbose_name': 'Choice', 'verbose_name_plural': 'Choices'},
        ),
        migrations.AddField(
            model_name='choice',
            name='position',
            field=models.IntegerField(default=1, verbose_name='Position'),
            preserve_default=False,
        ),
    ]
