# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-23 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20170723_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='icon',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default=1, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
