# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-23 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20170723_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['position'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AddField(
            model_name='course',
            name='position',
            field=models.IntegerField(default=1, verbose_name='Position'),
            preserve_default=False,
        ),
    ]
