# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-25 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20170725_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['position', 'name'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterField(
            model_name='course',
            name='position',
            field=models.IntegerField(blank=True, unique=True, verbose_name='Position'),
        ),
    ]
