# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-25 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20170725_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('r', 'Removed')], default='p', max_length=1),
        ),
    ]
