# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-23 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20170723_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='Position')),
                ('creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['position'],
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
            },
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['creation'], 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='videos',
        ),
        migrations.AddField(
            model_name='slide',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slide_lesson', to='courses.Lesson', verbose_name='Lesson'),
        ),
        migrations.AddField(
            model_name='slide',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slide_question', to='courses.Question', verbose_name='Question'),
        ),
    ]
