# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-23 22:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0011_auto_20170723_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='Lesson')),
                ('slide', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Slide', verbose_name='Slide')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ('-creation',),
                'verbose_name': 'Slide History',
                'verbose_name_plural': 'Slide History',
            },
        ),
    ]
