# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-23 23:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0012_slidehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningObjectHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='Lesson')),
            ],
            options={
                'ordering': ('-creation',),
                'verbose_name': 'Learning Object History',
                'verbose_name_plural': 'Learning Object History',
            },
        ),
        migrations.RenameModel(
            old_name='Slide',
            new_name='LearningObject',
        ),
        migrations.RemoveField(
            model_name='slidehistory',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='slidehistory',
            name='slide',
        ),
        migrations.RemoveField(
            model_name='slidehistory',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='learningobject',
            options={'ordering': ['position'], 'verbose_name': 'Learning Object', 'verbose_name_plural': 'Learning Objects'},
        ),
        migrations.DeleteModel(
            name='SlideHistory',
        ),
        migrations.AddField(
            model_name='learningobjecthistory',
            name='slide',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='courses.LearningObject', verbose_name='LearningObject'),
        ),
        migrations.AddField(
            model_name='learningobjecthistory',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
