# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-23 23:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20170723_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningobjecthistory',
            old_name='slide',
            new_name='learning_object',
        ),
    ]
