# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-23 23:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20170723_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningobjecthistory',
            name='lesson',
        ),
    ]
