# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-24 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_remove_learningobjecthistory_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introduction',
            name='question',
        ),
        migrations.DeleteModel(
            name='Introduction',
        ),
    ]
