# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='Please enter you first name.', max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='Please enter you last name.', max_length=100, verbose_name='Last Name'),
        ),
    ]
