# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20170503_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=b'uploads/profile_image/%Y/%m/%d', verbose_name='Profile Image'),
        ),
    ]
