# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default=b'/static/authentication/img/profile.png', null=True, upload_to=b'uploads/profile_image/%Y/%m/%d', verbose_name='Profile Image'),
        ),
    ]
