# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20170313_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default=b'/media/files/no_avatar.png', upload_to=b'uploads/profile_image/%Y/%m/%d', verbose_name='Profile Image'),
        ),
    ]
