# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='Profile Image'),
        ),
    ]
