XXXXXXXXX
  XXX XXXXXXXXXXXXXXXX
    XXX X XXXXX XXXXX XX XXXXX XXXXX XXXXXXXXXXX
  XXXXX

  XXX
    XXX XXX XXXXX XXXXXX XX XXXXX XXXXX XXXXXXX XXXXXXXXXX XXXX XXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXX XXXXXXXXXXXX XXXXXXXX XXXXXXX XXXX XXXXXX XX XXXXXXXXXXXXXXXXX XXXX XXXXXX XX XXX XXXX XXXX XXXX XXXXX XXX XXXXXXXXX XX XXX XXXXXXXXXXXX
  XXXX

BBBBBBBBB BB BBBBBBB
XXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXX XXXXX XX XX XXXXXXXXXXXXX
  XXXXXXXXXXX XXXX
XXX
BBBBBBBBBBBB

  XXXX
    XXX XX X XXXXXXXXXXX XXXXXXXXX
  XXXXX

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB

  XXXX
    XXX XXX XXXX XX XXX XXXXXXXX XXX XXXXXXXXX
  XXXXX

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB

  XXXX
    XXX XXXXX XXXXXX XXX XX XXXXX XXXXXXXXXX XX X XXXXXXXX XXXXXX XX XXXXX
  XXXXX

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
XXXXXXXXXX