XXXXXXXXX
  XXX XXXXXXXXXXXXXX
    XXX X XXXXX XXXXX XX XXXX XXXXXXXX XXXXXXXXXXX
  XXXXX

  XXX
    XXXX XXXXXXX XXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXX XXXXXXX XXX XXX XX XXX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXX XXX XX XXXXXX XX XXXX XXXXXXXXXXXX XXXXXXXX
  XXXX

  XXXX
    XXX XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XX XXXX XX XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
  XXXXX

  XXX
    XXXX XXXXXXX XXXX XXXXXXXXXXXXX XXX XXX XXXXX XX XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XX XXX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXXX
  XXXX
XXXXXXXXXX