XXXXXXXXX
  XXX XXXXXXXXXXXXXXXXX
    XXX XXX X XXXX XXXXXXX XXXXXXX X XXXXXXXXXXXX
  XXXXX

  XXX
    XXXXXXX XXXXXXXX XXXXXXXXXX X XXXXXXXXXXX XX XXXXXXX XXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXX XX XXXXXX X XXXX XXXXXX XXXXXXXX XXX XXXXXXXXXXX XXXXXXX XX X XXXXXX XX XXXXXXX XX XXX XXXXXXXXXXX XX XXX XXX XXXXX X XXXXX XXXXXXXXXXX XXXXXXX
  XXXX

BBBBBBBBB BB BBBBBBB
XXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXX XXXXXXX XX XXXXXXX
XXX
BBBBBBBBBBBB

  XXXX
    XX XXXXX XXXXXX XX XXXXX XXXXXXXXX XXXXXXX XX XX XXXXXXXXXXX
  XXXXX

  XXX
    XXXX XXXXXXX XXXXX XXXX XXX XX XXX XXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXX XXXXX XXXXXX XX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX

  XXX
    XXXX XXXX XXXX XXXX XXX XXXXX XX XXXXXXXX XXXXXXXX XX XXX XXXXXXX XXXX XXX XXXXXX XXX XXXXX XXXXXX XX XXXXXXX XXXX XXXXXXXX XXXXXXXXXX XXX XX XXXXX
  XXXX

  XXXX
    X XX XXXXX XXXXX XXX X XXXXX XXXX X XXXXXXXXXXXX
  XXXXX

  XXX
    XXXX XXXXXXX XXXXXXXX XXXXXXXXXXXX XXX XXX XXXXXXXXXXXXXXX XXX XXXX XXXXX XXXX XX XXX XX XXX XXXXXXXXXXX XXXXXX XX XXX XXX XXXXX X XXXXXX XXXXXXX
  XXXX

  XXXX
    XXX X XXX XX XXXXXX XXXXXXX X XXXXX XXXXX XX XX XXXXXXXXXXXX
  XXXXX

  XXX
    XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXX XXX XX XXXX XX X XXXX XXXXXX XXXXXXX XX XXXX X XXXXXX XX XXX XXXX XXXX XXXXXXXXXXXX XXX XXXXXXXXXXXXXXX XX XXX XXXX XXXXXX XXXXXX XXXXX XXX XXXXXXXXXXXXXXXXXX XX XXX XXXXXXXXXXX XXXXXXX
  XXXX

BBBBBBBBB BB BBBBBBB
XXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXX X
    XXX XXXXX XX XXX XXXXX XX XXX XXXXXX
    XXXXX XXXXXXX XX XXXXXXX
  X
XXX
BBBBBBBBBBBB

  XXXX
    XXX X XXXXXX XXX XXX XXXXXXXXXXX XXXXXX
  XXXXX

  XXX
    XXXX XXXXX XXXXXXX XXXXXXXXXXXX XXXX X XXXXXX XXXXXXXXX XXX XX XXXXXXXXXXXXXX XXX XXXXXXXXXXX XXXXXX XXXX XX XXXXXX XXXXXXX XXX XXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XX XXX XXX XXXX XX XXXXXX XXX XX XX XXXXXXXXXX
  XXXX

BBBBBBBBB BB BBBBBBB
XXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXX XXXXXX X
    XX XXXXXXXX XXX XXX X XX XXXXXX XXX XXXXXX XXXXXXXXXXX XXXXXX
      XXXXXX XXXXXXX XXXXXX XXXXXXXXXXX XXXXXX
    X

    XXXXXX XXXXXXXXXX
  X
XXX
BBBBBBBBBBBB

  XXX
    XXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXX XXX XXXXXXXXXXX XXXX XX XXXXXXXXX XXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XX XXX XXXXXX XXXX XXX XXX XXXXXXXXX XXX XXXXXXX XX XXXX XXXXXXXXXX XXXXX XXXX XX XXXXXXXXX XX XXX XXXXXXXXX XXXXX XXXXXXXX XXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX XXXXX XXXXXXXXXXX XXXXX XXXX XXXXXXX
  XXXX

  XXXX
    XX XXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXX XX XXXXXXXX XXXXXXXX
  XXXXX

  XXX
    XXXXXXX XXXX XXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XX XXXXX XXXXX XXX XXX XXXXXXXX XXXXXXX XXX XXXX XXXXXXXXX XX XXX XXXXXXXXX XX XXXXX XXXXXXXX XX XXXXXXXX XXXXXXXXX XXX XXXX XX XXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXX XXXXX XX XXX XXX XXXX XXXXXX XX XXXXX XX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XX XXXXX XXXXXX
  XXXX
XXXXXXXXXX
