XXXXXXXXX
  XXX XXXXXXXXXXXXXXXXXXXXXXX
    XXX XXX X XXXXXXXXX XXX XXX XXXXXXXXXX XXX XXXXXXXXXX
  XXXXX

  XXX
    XXXX X XXXXXXXXX XX XXXX XX XXX XXXX XXXXXXX XXXX XXXXXXX XXX XXXX XX XXX XXXXXX XX XXXXXXXX XXXX XXXX XXX XX XX XXXXXXXXX XX X XXXXXXXX XXXXXX XXXX  XXX XXX XXXXXXXX XXX XXXXXXX XX XXX XXXXXXXXX XX XXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XX X XXXXXXXXXX XXXXXXXXX
  XXXX

BBBBBBBBB BB BBBBBBB
XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX X
  XXXXXX XXXXXXXXXX
X

XXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXX XXXXXXXX
XXX
BBBBBBBBBBBB

  XXXX
    XXXXXXX XX XXXXX XXXXXXXXX XXXX X XXXXXX XX XXXXXX
  XXXXX

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB

  XXXX
    X XX XXXXX XXXX XX XX XXXXXXXXX XXXXXXXX XXX XX XXXXX XXXXXXXXXX XX
  XXXXX

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB

  XXXX
    XXX XXX X XXXXXX XXX XXXXXXXXX XXXXX XXX XXXXXXXXX XX XXXXXXXXXX
  XXXXX

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
XXXXXXXXXX