XXXXXXXXX
  XXX XXXXXXXXXXXXX
    XXXXXXXXXX XXXXXXX
  XXXXX

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
XXXXXXXXXX