# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-21 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('r', 'Removed')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
