# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-21 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_challenge_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('is_correct', '-last_modified'), 'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='correct',
            new_name='is_correct',
        ),
    ]
