# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-21 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_auto_20170721_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='level',
            field=models.CharField(choices=[('s', 'Severe'), ('i', 'Intermediate'), ('e', 'Easy')], default=1, max_length=1, verbose_name='Difficult level'),
            preserve_default=False,
        ),
    ]
