# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-21 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_challenge_level'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='Solution',
        ),
        migrations.AlterModelOptions(
            name='solution',
            options={'ordering': ('is_correct', '-last_modified'), 'verbose_name': 'Solution', 'verbose_name_plural': 'Solutions'},
        ),
    ]
