# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-22 01:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_auto_20170721_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solution',
            options={'ordering': ('-is_correct', 'last_modified'), 'verbose_name': 'Solution', 'verbose_name_plural': 'Solutions'},
        ),
    ]
