XXX
XXXXXXX XXXXXXX
XXXXXX XXXXXXX X XXXXXXX
XXXXX XXXXXXX
XXX

XXXXXXXX XXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXXX
      XXXXXXX
    XXXXX
    XX XXXXXXXXXXXXX
      XXXXXXX XXXXXXXX X XXXX XXXXXXX XX XXXXXXX XXXX XXXXX XXX XX XXXXXXXXX XX XX XXXX XXXXXX
    XXXX
  XXXXXX
XXXXXXXXXX

XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
      BBBBBBB BBBBBBBBBBBBBBBBB
      BBBBBBB BBBBBBBBBBBBBBBBB
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
      BBBBBBB BBBBBBBBBBBBBBBBBBBBB
      BBBBBBB BBBBBBBBBBBBBBBBBBB
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
      BBBBBBB BBBBBBBBBBBBBBBB
    XXXXXX
  XXXXXX
XXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX
XXXXXXXXX
