XXX
XXXXXXX XXXXXXX
XXXXXX XXXXXXX X XXXXXXX
XXXXX XXXXXXX
XXX

XXXXXXXX XXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXXX
      XXXXXXX
    XXXXX
  XXXXXX
XXXXXXXXXX

XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX

      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

    XXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX

      BBBBBBB BBBBBBBBBBBBBBBBBBBB

    XXXXXX
  XXXXXX
XXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX
XXXXXXXXX
