# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 05:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20170209_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='created_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_network_created_by', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
