# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20170222_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='page',
            field=models.URLField(blank=True, verbose_name='Page'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_text',
            field=models.TextField(verbose_name='Message'),
        ),
    ]
