# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20170301_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='report_text',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='solved',
            new_name='solved_in',
        ),
        migrations.AddField(
            model_name='report',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='report',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Name'),
        ),
    ]
