# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 15:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0005_auto_20170210_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.URLField(verbose_name='Page')),
                ('text', models.TextField(verbose_name='Text')),
                ('solved', models.BooleanField(default=False, verbose_name='Solved')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'ordering': ['-last_modified'],
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
    ]
