# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
