# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 00:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0007_report_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='solved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_solved_by', to=settings.AUTH_USER_MODEL, verbose_name='Solved by'),
        ),
    ]
