# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_report_solved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='text',
        ),
        migrations.AddField(
            model_name='report',
            name='report_text',
            field=models.TextField(default=1, verbose_name='Report text'),
            preserve_default=False,
        ),
    ]
