# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20170321_0535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='page',
        ),
    ]
