BBBB BBBB

XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
	XXXX
		XX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'Skip to main content of the page - Shortcut #1') XX
			 gettext(u'To Content')  XXX
		XXXX
	XXXXX
	XXXX
		XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'Skip to navigation of the page - Shortcut #2') XX
			 gettext(u'To Navigation')  XXX
		XXXX
	XXXXX
	XXXX
		XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'On/Off High Contrast - Shortcut #3') XX
			 gettext(u'High Contrast-OFF')  XXX
		XXXX
	XXXXX
	XXXX
		XX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'Increase Font - Shortcut #4') XX
			 gettext(u'Increase Font')  XXX
		XXXX
	XXXXX
	XXXX
		XX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'Decrease Font - Shortcut #5') XX
			 gettext(u'Decrease Font')  XXX
		XXXX
	XXXXX
XXXXX