BBBB BBBB

BBB BBB BB BBBBBBBBBBBB

XXX XXXXXXXXXX XXXXXXXXXXXX
	XXX XXXXXXXXXXXXXXX XXXXXXXX
		XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBXXXXXXXX XXXX X  XXXXX XXXXXXXXXXX
	XXXXX
	XXX XXXXXXXXXXXXXXX XXXXXXXX
		XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBXX gettext(u'About') XXXX
	XXXXX
	XXX XXXXXXXXXXXXXXX XXXXXXXX
		XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBXX gettext(u'Terms of Use') XXXX
	XXXXX
	XXX XXXXXXXXXXXXXXX XXXXXXXX
		XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBXX gettext(u'Privacy Policy') XXXX
	XXXXX
	XXX XXXXXXXXXXXXXXX XXXXXXXX
		XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBXX gettext(u'Contact Us') XXXX
	XXXXX
	XXX XXXXXXXXXXXXXXX XXXXXXXX
		XXXX XXXXXXXXXXXXXXXXX
			XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXBBBBBBBBBB
			
			XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XX
			XXXXXXX XXXXXXXXXXXXXXXX
			BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
			BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBB
			BBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBB BB BBBBBBBBB
			BBB BBBBBBBB BB BBBBBBBBB
			XXXXXXX XXXXXXXXBB BBBBBBBBBBBBB BB BBBBBBBBBBBBB XXXXXXXXXXXXXXXXXXX BBBBBX 
				
			XXXXXXXXX
			BBBBBB
			XXXXXXXXX
			# Translators: Label of a button that triggers language
			XXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXX gettext(u'Go') X XX
			XXXXXXX
		XXXXXX
	XXXXX
XXXXX