BBBB BBBB
BBBB BBBBBBBB

BBB BBBBBB BB BBBBBBBBBBBBBBBBBB
	
BBBBBB

BBB BBBBB BB BBBBBBBBBBBBBBBBBBB
	BB BBBBBBBBBBBBBBBBB
		BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
	BBBB BBBBBBBBBBBBBB
		BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
	BBBB BBBBBBBBBBBBBBB
		BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
	BBBB BBBBBBBBBBBBBBBBBBBBBBBB
		BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
	BBBB BBBBBBBBBBBBB
		BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
	BBBB BBBBBBBBBBBBB
		BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
	BBBB BBBBBBBBBBBBBBBBB
		BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
	BBBB BBBBBBBBBBBBBB
		BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
	BBBB BBBBBBBBBBBBBBB
		BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
	BBBB BBBBBBBBBBBBB
		BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
	BBBB BBBBBBBBBBBBBBBBB
		BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
	BBBB BBBBBBBBBBBBBBBBB
		BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
	BBBB
		BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
	BBBBB
	XXX XXXXXXXXXXXXXXXXX
BBBBBB