BBBB BBBB
BBBB BBBBBBBB

BBB BBBBBB BB BBBBBBBBBBBBBBBBBB
	
BBBBBB

BBB BBBBB BB BBBBBBBBBBBBBBBBBBB
	BB BBBBBBBBBBBBBBBBB
		BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
	BBBB BBBBBBBBBBBBBB
		BBBBBBB BBBBBBBBBBBBBBBBBBB
	BBBB BBBBBBBBBBBBBBB
		BBBBBBB BBBBBBBBBBBBBBBBBBBB
	BBBB BBBBBBBBBBBBBBBBBBBBBBBB
		BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
	BBBB BBBBBBBBBBBBB
		BBBBBBB BBBBBBBBBBBBBBBBBB
	BBBB BBBBBBBBBBBBB
		BBBBBBB BBBBBBBBBBBBBBBBBB
	BBBB BBBBBBBBBBBBBBBBB
		BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
	BBBB BBBBBBBBBBBBBB
		BBBBBBB BBBBBBBBBBBBBBBBBBB
	BBBB BBBBBBBBBBBBBBB
		BBBBBBB BBBBBBBBBBBBBBBBBBBB
	BBBB BBBBBBBBBBBBB
		BBBBBBB BBBBBBBBBBBBBBBBBB
	BBBB BBBBBBBBBBBBBBBBB
		BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
	BBBB BBBBBBBBBBBBBBBBB
		BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
	BBBB
		BBBBBBB BBBBBBBBBBBBBBBBBBB
	BBBBB
	XXX XXXXXXXXXXXXXXXXX
BBBBBB