BBBB BBBB BBBBBB

XXXX XXXXXXXXXXXXXXX
	BBBBBBB BBBBBBBBBBBBBBBBBBBBB
	XXXX XXXXXXXXXXXXX
		XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXX XXXX XXX XXXXX XX
			XX XXXXXXBBB BBBBBBBBBBXX
				XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXX XX
			XXXX
		XXXXXX
		XXXX XXXXXXXXXXXXXX XXXXXX
	XXXXXX
XXXXXX


XXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXX
	XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
	XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
		XX XXXXXXBBB BBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXX
			XX XXXXXXXXX XXXXXXXXXXXXX
			 gettext(u'Home') 
	  	XXXX
		XXX XXXXXXXXXX XXXXXXXXXXXX
			BB BBBBBBBBBBBBBBBBBBBBBBBBB
			XXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX
				XX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
					XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
					 gettext(u'Extra') 
				XXXX
				XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
					XX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXX
						XX XXXXXXXXX XXXXXXXXXXXXXX
						 gettext(u'Django Admin') 
					XXXX
					XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
						XX XXXXXXXXX XXXXXXXXXXXXXXXXX
						 gettext(u'Rosetta') 
					XXXX
				XXXXXX
			XXXXX
			BBBBB
		XXXXX

		XXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX
			BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
			XXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX
				XX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
					XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
					
				XXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXX
					XX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBXX
						XX XXXXXXXXX XXXXXXXXXXXXX
						 gettext(u'Profile') 
					XXXX
					XX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
						XX XXXXXXXXX XXXXXXXXXXXX
						 gettext(u'Change password') 
					XXXX
					XX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
						XX XXXXXXXXX XXXXXXXXXXXXXXXXX
						 gettext(u'Logout') 
					XXXX
				XXXXXX
			XXXXX
			BBBB
				XXX XXXXXXXXXXXXXXX XXXXXXXX
					XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
						XX XXXXXXXXX XXXXXXXXXXXXXXXX
						 gettext(u'Login') 
					XXXX
				XXXXX
			BBBBB
		XXXXX
	XXXXXX
XXXXXX
