BBBB BBBB

XXXX XXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
	XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXX
				XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
					XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXXXXX
				XXX XXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXX
				XXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXX
				XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Close') XXXXXXXXX
			XXXXXX
		XXXXXX
	XXXXXX
XXXXXX