XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXXXXXXXXXX XXX XXXXX XXXX XXX XXX XXXX XX XXX XXXXX XX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XX XXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXX XXXX XX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX XX XXXX XXXXXXXX XX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXX
  XXXXXX
XXXXXXXXX

XXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

BB BBBBBBBBBBB
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBB
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBB

BB BBBBBBBBBBB
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBB
  BBB BBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXXX XXXXXXXXXXXXXXXXX
  BBBBBB
BBBBB

XXXX XXXX XXXXXXXX XXXX XXX XXXXXXXXXXXXXXX XXXXXXX X XXX XXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

BB BBBBBBBBBBB BB BBBBBB
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXX XX XXXXXXX XXX XXXX XXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXX
XX
XXXXXXXXX
BBBBB

XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXX X
  XXX XXXXXXX
  XXX XXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXX
  XXXXXXXXXXX XXXXXXXX
XX
XXXXXXXXX
