XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX

XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
  BBB BBBBB BB BBBBBBBBBBBBB
  BBBBBB BBBB B BBBBBBBBBBB B BBBBB
  BBBBBB BBBB B BBBBBBBBBBB B BBBBBBBB B BBBBBBBB B BB BBB BB BBBBBBBBBB B BBBBBBBB B BBBBBBBB B BB BBB
  BBBBBB BBBBBB B BBB

  BB BBBBBBBB BBBBBBBB BBBB
    BBBBBB BBBBBB B BBBBBBBB
  BBBBB

  XXXX XXXXXXXXXXXXXXXXXX XX
    BB BBBB BB BBBBBBBBBB
        XX XXXXXXXXXXXXXXXXXXX XXXXXXX FFFFFFFF  FFFFFFFF F FF FFFXXX
      BBBB
        XX XXXXXXXXXXXXXXXXXXX XXXXXXX FFFFFFFF  FFFFFFFF F FF FFFX FFFFFFFF  FFFFFFFF F FF FFF  FFFFFFFFFF  FFFFFFFF  FFFFFFFF F FF FFFXX
      BBBBB
        
      XXXX

      XXX XXXXXXXXXX XXXXXXXXXXXX
        BBB BBB BB BBBBBBBBBBB
          BBBBBB BBBB B BBBBBBBBB B BBBBBBBB B BBBBBBBB B BB BBB B BBBBBBBBBBBBBBBBB
          BBBBBBB BBBBXBBBBBBBBBB
          BBBBBB BBBBBB B BBB

          BB BBBBBBBB BBBBBBBB BBBB
            BBBBBB BBBBBB B BBBBBBB BBBBBBBBBBBBBBBBBB
          BBBBB

          XXX XXXXXXXXX
            XX XXXXXXX FFFFFFFF  FFFFFFFF F FF FFFX FFFFFFFF  FFFFFFFF F FF FFF  FFFFFFFFFFFFFFFFFXXX
              
            XXXX

             #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #

          XXXXX
        BBBBBB
      XXXXX
    XXXXXX
  BBBBBB
XXXXXX
