XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
     #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #


    XXXXX
      XXXX XXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
          XXXXXXXXX
        XXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXX XXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXX XXXXXXXX
            XX XXXXXXXXXXXXXXX XXXXXXXX BB BBBBBBBBBBB BB BBBBBBXXXXXXBBBBBX XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX
          XXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXX XXXXXXXX BB BBBBBBBBBBB BB BBBBBBXXXXXXBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX
          XXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXX XXXXXXXX BB BBBBBBBBBB BB BBBBBBBBBBXXXXXXBBBBBX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX
          XXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXXX
          XXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX
          XXXXX
          XXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX
          XXXXX
        XXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXX
