BB BBBBBBBBBB BB BBBBBBBBBBBBBBBBB
  XXXXXXXXXXX XXXXXXXXXXXX
  XX XXXXXXXXXXXXX
    XX XXXXXXXX XX XXXXXXXXXX XXXXXXXXX XXX XX XXXXXXXX XXX XXX XXX XXXX XXXXX XXXXXXXXX XXX XXXXXXXXX XXX XXXXX
  XXXX
BBBBB BBBBBBBBBB BB BBBBBBBB
  XXXXXXXXXXXXXXX
  XX XXXXXXXXXXXXX
    XXXXXXX XXX XXXXXXXXXXX XXXX XXXXX XXXX XXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXX XXXXX
  XXXX
BBBBB BBBBBBBBBB BB BBBBBBBBB
  XXXXXXXXXXXXXXXX
  XX XXXXXXXXXXXXX
    XXXXXX XXX XXXXXXXXXX XXXXXXX XXXX XXXX XX XXX XXXX XXXXXXXX XXXX XXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXX XXX XXXXX
  XXXX
BBBBB BBBBBBBBBB BB BBBBBBBBBBBB
  XXXXXXXXXXXXXXXXXXX
  XX XXXXXXXXXXXXX
    XXXX X XXXXX XXXXXXXX XXXXXXXXXX XXXXX XX XXXXXXX XXXXXXXX XXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXX XXXXXXX XXX XXXX XXXXX
  XXXX
BBBBB BBBBBBBBBB BB BBBBBBBBBBB
  XXXXXXXXXXXXXXXXXX
  XX XXXXXXXXXXXXX
    XXXXXXXXX XXXXXXXX XXXXXX XX XXXXXXXXXXXXXXXXX XXXX X XXXXXX XXXXXXX XX XXXXXX XXX XXXXXXXXX XX XXXXXX XXXXXXXXXX XXXXXXXXXXXXX
  XXXX
BBBBB BBBBBBBBBB BB BBBBBBBBBBBB
  XXXXXXXXXXXXXX XXXXXXXXXXXX
  XX XXXXXXXXXXXXX
    XXXXX XXXXXXXXXXX XXXXXXXXXX XX XXXX XXXX XXXX X XXXXX XXXXXX XXXXXX XXXXXXXX XXXXXX XXXXXXX XXXX XXXX XX XXX XX XXXX
  XXXX
BBBBB BBBBBBBBBB BB BBBBBBB
  XXXXXXXXXXXXXX
  XX XXXXXXXXXXXXX
    XXXXX XXXXX XXX XXXXXXXXX XXXXXXXX XXXX XXX XXXXXXXXXXX XXXXXX XXX XXXX XXX XXX XX XXX XXX XXXXXXXXX XXXXXX
  XXXX
BBBBB BBBBBBBBBB BB BBBBBBBBBBB
  XXXXXXXXXXXXXXXXXX
  XX XXXXXXXXXXXXX
    XXXXXXXX XX XXX XX XXXXXXX XXXX XXXXXXXXX XXXX XX XXXX XXXX XXXXXXXX XX XXXXX XXXXXXXX XXXXXX XXXX XXX XXXXXX XXXX XXXXXXXX
  XXXX
BBBBB BBBBBBBBBB BB BBBBBBBBBBBBBB
  XXXXXXXX XX XXXXXXX XXXXXXXXX
  XX XXXXXXXXXXXXX
    X XXXX XX XXX XXXXXXX XXXX XXXX XXXXXXXXX XX XXXXXXXXX XXXXXXXXX XXXXX
  XXXX
BBBBB
