XXXXXXXXX
  XXX XXXXXXXXXXXXXXXXXXX
    XXX XXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX

  XX XXXXXXXXXXXX XXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX XXXXXXXX
    XXXX XXX XXXX XXXXXXXX XX XXXXXXX XXXXXX XXX XX XXXX XXXXXXXXX XX XXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XX
    XXXXXXXX
  XXXX

  XXX
    XX XXX XXXXX XXXXXXX XXXXXXXX XX XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXX XXXXXXX XXXXXXXX X XXXXXX XXXX XXXXXX XXX XXXXX XXXXX XXXXXXXX
    XXX XXX XXXXXXX XXXXXXXXX XXX XXX XXXXXXXXX XX XX XXXXXXXXXXX XXXX XXX
    XXXX XXXXXXXX XX XXX XXXXXXXXXXXXXXXXXXXX XXXXXX XX XXX
    XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
  XXXX

  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXX
        XXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX

        XXXXXXXXXXXXXX
        XXXX
          X XXXXXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXX
        XXXXX
      XXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXX
        XXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX

        XXXXXXXXXXXXXXXXXX
        XXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
      XXXXX
    XXXXXX
  XXXXXX
XXXXXXXXXX