# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Number')),
                ('image', models.ImageField(upload_to=b'uploads/level_image/%Y/%m/%d', verbose_name='Image')),
            ],
            options={
                'ordering': [],
                'verbose_name': 'Level',
                'verbose_name_plural': 'Levels',
            },
        ),
        migrations.AddField(
            model_name='levelmanager',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gamification.Level', verbose_name='Level'),
            preserve_default=False,
        ),
    ]
