# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_auto_20170313_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoremanager',
            name='reputation',
            field=models.PositiveIntegerField(default=0, verbose_name='Reputation'),
        ),
        migrations.AddField(
            model_name='scoremanager',
            name='rp',
            field=models.PositiveIntegerField(default=0, verbose_name='RP'),
        ),
        migrations.AddField(
            model_name='scoremanager',
            name='skill',
            field=models.PositiveIntegerField(default=0, verbose_name='Skill'),
        ),
        migrations.AddField(
            model_name='scoremanager',
            name='xp',
            field=models.PositiveIntegerField(default=0, verbose_name='XP'),
        ),
    ]
