# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_auto_20170313_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rankingmanager',
            name='user',
        ),
        migrations.DeleteModel(
            name='RankingManager',
        ),
    ]
