BBBB BBBB
XXXXXX XXXXXX XXXXXXXXXXXXXXXXX
	XXXX XXXXXXXXXXXX
		
		BB BBBBBBBBBBBBBBBBBBBB
			XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'This field is required!') XXXXXXXXXX
		BBBBBX
	XXXXXX
XXXXXXXX